// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Buttons() {
    // Test name: Buttons
    // Step # | name | target | value
    // 1 | open | https://demoqa.com/elements | 
    driver.Navigate().GoToUrl("https://demoqa.com/elements");
    // 2 | setWindowSize | 786x824 | 
    driver.Manage().Window.Size = new System.Drawing.Size(786, 824);
    // 3 | click | id=item-4 | 
    driver.FindElement(By.Id("item-4")).Click();
    // 4 | click | xpath=//div[3]/button | 
    driver.FindElement(By.XPath("//div[3]/button")).Click();
    // 6 | doubleClick | id=doubleClickBtn | 
    {
      var element = driver.FindElement(By.Id("doubleClickBtn"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    // 7 | assertText | id=dynamicClickMessage | You have done a dynamic click
    Assert.Equal(driver.FindElement(By.Id("dynamicClickMessage")).Text, "You have done a dynamic click");
    // 8 | assertText | id=doubleClickMessage | You have done a double click
    Assert.Equal(driver.FindElement(By.Id("doubleClickMessage")).Text, "You have done a double click");
    // 9 | assertText | id=rightClickMessage | You have done a right click
    Assert.Equal(driver.FindElement(By.Id("rightClickMessage")).Text, "You have done a right click");
  }
}
