// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Checkbox() {
    // Test name: Checkbox
    // Step # | name | target | value
    // 1 | open | https://demoqa.com/elements | 
    driver.Navigate().GoToUrl("https://demoqa.com/elements");
    // 2 | setWindowSize | 1054x808 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 808);
    // 3 | click | id=item-1 | 
    driver.FindElement(By.Id("item-1")).Click();
    // 4 | click | css=.rct-icon-expand-close | 
    driver.FindElement(By.CssSelector(".rct-icon-expand-close")).Click();
    // 5 | click | css=.rct-node-collapsed:nth-child(1) .rct-collapse > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node-collapsed:nth-child(1) .rct-collapse > .rct-icon")).Click();
    // 6 | click | css=.rct-node-parent:nth-child(2) .rct-collapse > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node-parent:nth-child(2) .rct-collapse > .rct-icon")).Click();
    // 7 | click | css=.rct-node:nth-child(3) .rct-collapse > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node:nth-child(3) .rct-collapse > .rct-icon")).Click();
    // 8 | click | css=.rct-node-collapsed:nth-child(1) .rct-collapse > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node-collapsed:nth-child(1) .rct-collapse > .rct-icon")).Click();
    // 9 | click | css=.rct-icon-expand-close > path | 
    driver.FindElement(By.CssSelector(".rct-icon-expand-close > path")).Click();
    // 10 | click | css=#tree-node > ol > .rct-node > .rct-text .rct-checkbox > .rct-icon | 
    driver.FindElement(By.CssSelector("#tree-node > ol > .rct-node > .rct-text .rct-checkbox > .rct-icon")).Click();
    // 11 | click | css=.col-md-6 | 
    driver.FindElement(By.CssSelector(".col-md-6")).Click();
    // 12 | assertText | id=result | You have selected :\nhome\ndesktop\nnotes\ncommands\ndocuments\nworkspace\nreact\nangular\nveu\noffice\npublic\nprivate\nclassified\ngeneral\ndownloads\nwordFile\nexcelFile
    Assert.Equal(driver.FindElement(By.Id("result")).Text, "You have selected :\\\\nhome\\\\ndesktop\\\\nnotes\\\\ncommands\\\\ndocuments\\\\nworkspace\\\\nreact\\\\nangular\\\\nveu\\\\noffice\\\\npublic\\\\nprivate\\\\nclassified\\\\ngeneral\\\\ndownloads\\\\nwordFile\\\\nexcelFile");
    // 13 | click | css=#tree-node > ol > .rct-node > .rct-text .rct-checkbox > .rct-icon | 
    driver.FindElement(By.CssSelector("#tree-node > ol > .rct-node > .rct-text .rct-checkbox > .rct-icon")).Click();
    // 14 | click | css=.rct-node:nth-child(2) .rct-node:nth-child(1) .rct-node:nth-child(2) .rct-checkbox > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node:nth-child(2) .rct-node:nth-child(1) .rct-node:nth-child(2) .rct-checkbox > .rct-icon")).Click();
    // 15 | click | css=.rct-node:nth-child(2) > ol > .rct-node:nth-child(3) .rct-checkbox > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node:nth-child(2) > ol > .rct-node:nth-child(3) .rct-checkbox > .rct-icon")).Click();
    // 16 | click | css=.rct-node:nth-child(3) .rct-node:nth-child(2) .rct-checkbox > .rct-icon | 
    driver.FindElement(By.CssSelector(".rct-node:nth-child(3) .rct-node:nth-child(2) .rct-checkbox > .rct-icon")).Click();
    // 17 | click | id=result | 
    driver.FindElement(By.Id("result")).Click();
    // 18 | assertText | id=result | You have selected :\nangular\nclassified\nexcelFile
    Assert.Equal(driver.FindElement(By.Id("result")).Text, "You have selected :\\\\nangular\\\\nclassified\\\\nexcelFile");
    // 19 | click | css=.rct-icon-collapse-all > path | 
    driver.FindElement(By.CssSelector(".rct-icon-collapse-all > path")).Click();
    // 20 | click | css=.rct-icon-half-check > path | 
    driver.FindElement(By.CssSelector(".rct-icon-half-check > path")).Click();
    // 21 | click | id=result | 
    driver.FindElement(By.Id("result")).Click();
    // 22 | assertText | id=result | You have selected :\nhome\ndesktop\nnotes\ncommands\ndocuments\nworkspace\nreact\nangular\nveu\noffice\npublic\nprivate\nclassified\ngeneral\ndownloads\nwordFile\nexcelFile
    Assert.Equal(driver.FindElement(By.Id("result")).Text, "You have selected :\\\\nhome\\\\ndesktop\\\\nnotes\\\\ncommands\\\\ndocuments\\\\nworkspace\\\\nreact\\\\nangular\\\\nveu\\\\noffice\\\\npublic\\\\nprivate\\\\nclassified\\\\ngeneral\\\\ndownloads\\\\nwordFile\\\\nexcelFile");
    // 23 | click | css=.rct-icon-check > path | 
    driver.FindElement(By.CssSelector(".rct-icon-check > path")).Click();
    // 24 | click | css=.rct-icon-expand-close | 
    driver.FindElement(By.CssSelector(".rct-icon-expand-close")).Click();
    // 25 | click | css=.rct-icon-expand-all > path | 
    driver.FindElement(By.CssSelector(".rct-icon-expand-all > path")).Click();
  }
}
