// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void RadioButton() {
    driver.Navigate().GoToUrl("https://demoqa.com/elements");
    driver.Manage().Window.Size = new System.Drawing.Size(784, 824);
    driver.FindElement(By.CssSelector(".show #item-2 > .text")).Click();
    driver.FindElement(By.CssSelector(".custom-control:nth-child(2) > .custom-control-label")).Click();
    Assert.True(driver.FindElement(By.Id("yesRadio")).Selected);
    Assert.Equal(driver.FindElement(By.CssSelector(".mt-3")).Text, "You have selected Yes");
    driver.FindElement(By.CssSelector(".custom-control:nth-child(3) > .custom-control-label")).Click();
    Assert.True(driver.FindElement(By.Id("impressiveRadio")).Selected);
    Assert.False(driver.FindElement(By.Id("yesRadio")).Selected);
    Assert.Equal(driver.FindElement(By.CssSelector(".mt-3")).Text, "You have selected Impressive");
  }
}
