// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void UploadandDownload() {
    // Test name: Upload and Download
    // Step # | name | target | value
    // 1 | open | https://demoqa.com/elements | 
    driver.Navigate().GoToUrl("https://demoqa.com/elements");
    // 2 | setWindowSize | 1057x808 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1057, 808);
    // 3 | click | css=.show #item-7 > .text | 
    driver.FindElement(By.CssSelector(".show #item-7 > .text")).Click();
    // 4 | runScript | window.scrollTo(0,248) | 
    js.ExecuteScript("window.scrollTo(0,248)");
    // 5 | click | id=downloadButton | 
    driver.FindElement(By.Id("downloadButton")).Click();
    // 6 | type | id=uploadFile | C:\Users\a875026\Downloads\sampleFile.jpeg
    driver.FindElement(By.Id("uploadFile")).SendKeys("C:\\Users\\a875026\\Downloads\\sampleFile.jpeg");
    // 7 | assertText | id=uploadedFilePath | C:\fakepath\sampleFile.jpeg
    Assert.Equal(driver.FindElement(By.Id("uploadedFilePath")).Text, "C:\\\\fakepath\\\\sampleFile.jpeg");
    // 8 | close |  | 
    driver.Close();
  }
}
