// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void WebTables() {
    // Test name: WebTables
    // Step # | name | target | value
    // 1 | open | https://demoqa.com/elements | 
    driver.Navigate().GoToUrl("https://demoqa.com/elements");
    // 2 | setWindowSize | 784x824 | 
    driver.Manage().Window.Size = new System.Drawing.Size(784, 824);
    // 3 | click | id=item-3 | 
    driver.FindElement(By.Id("item-3")).Click();
    // 4 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 5 | type | id=searchBox | cierra
    driver.FindElement(By.Id("searchBox")).SendKeys("cierra");
    // 6 | assertText | css=.rt-tr-group:nth-child(1) .rt-td:nth-child(1) | Cierra
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(1) .rt-td:nth-child(1)")).Text, "Cierra");
    // 7 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 8 | type | id=searchBox | kierra
    driver.FindElement(By.Id("searchBox")).SendKeys("kierra");
    // 9 | assertText | css=.rt-tr-group:nth-child(1) .rt-td:nth-child(1) | Kierra
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(1) .rt-td:nth-child(1)")).Text, "Kierra");
    // 10 | click | css=.rt-tr-group:nth-child(2) .rt-td:nth-child(1) | 
    driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(2) .rt-td:nth-child(1)")).Click();
    // 11 | click | css=.container > .row | 
    driver.FindElement(By.CssSelector(".container > .row")).Click();
    // 12 | click | css=.rt-tr-group:nth-child(2) .rt-td:nth-child(1) | 
    driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(2) .rt-td:nth-child(1)")).Click();
    // 13 | assertText | css=.rt-tr-group:nth-child(2) .rt-td:nth-child(1) |  
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(2) .rt-td:nth-child(1)")).Text, " ");
    // 14 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 15 | type | id=searchBox | .
    driver.FindElement(By.Id("searchBox")).SendKeys(".");
    // 16 | click | css=#edit-record-2 path | 
    driver.FindElement(By.CssSelector("#edit-record-2 path")).Click();
    // 17 | click | id=firstName | 
    driver.FindElement(By.Id("firstName")).Click();
    // 18 | type | id=firstName | Carlos
    driver.FindElement(By.Id("firstName")).SendKeys("Carlos");
    // 19 | type | id=lastName | Espinoza
    driver.FindElement(By.Id("lastName")).SendKeys("Espinoza");
    // 20 | type | id=userEmail | test@test.com
    driver.FindElement(By.Id("userEmail")).SendKeys("test@test.com");
    // 21 | type | id=age | 15
    driver.FindElement(By.Id("age")).SendKeys("15");
    // 22 | type | id=salary | 1
    driver.FindElement(By.Id("salary")).SendKeys("1");
    // 23 | type | id=department | test
    driver.FindElement(By.Id("department")).SendKeys("test");
    // 24 | click | id=submit | 
    driver.FindElement(By.Id("submit")).Click();
    // 25 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 26 | type | id=searchBox | carlos
    driver.FindElement(By.Id("searchBox")).SendKeys("carlos");
    // 27 | assertText | css=.rt-tr-group:nth-child(1) .rt-td:nth-child(1) | Carlos
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(1) .rt-td:nth-child(1)")).Text, "Carlos");
    // 28 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 29 | click | css=#delete-record-2 path | 
    driver.FindElement(By.CssSelector("#delete-record-2 path")).Click();
    // 30 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 31 | type | id=searchBox | carlos
    driver.FindElement(By.Id("searchBox")).SendKeys("carlos");
    // 32 | assertText | css=.rt-tr-group:nth-child(1) .rt-td:nth-child(1) |  
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(1) .rt-td:nth-child(1)")).Text, " ");
    // 33 | click | id=addNewRecordButton | 
    driver.FindElement(By.Id("addNewRecordButton")).Click();
    // 34 | click | id=firstName | 
    driver.FindElement(By.Id("firstName")).Click();
    // 35 | type | id=firstName | test
    driver.FindElement(By.Id("firstName")).SendKeys("test");
    // 36 | type | id=lastName | test
    driver.FindElement(By.Id("lastName")).SendKeys("test");
    // 37 | type | id=userEmail | test@test.com
    driver.FindElement(By.Id("userEmail")).SendKeys("test@test.com");
    // 38 | type | id=age | 18
    driver.FindElement(By.Id("age")).SendKeys("18");
    // 39 | type | id=salary | 19
    driver.FindElement(By.Id("salary")).SendKeys("19");
    // 40 | type | id=department | 20
    driver.FindElement(By.Id("department")).SendKeys("20");
    // 41 | click | id=submit | 
    driver.FindElement(By.Id("submit")).Click();
    // 42 | click | id=searchBox | 
    driver.FindElement(By.Id("searchBox")).Click();
    // 43 | type | id=searchBox | .
    driver.FindElement(By.Id("searchBox")).SendKeys(".");
    // 44 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(1) | test
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(1)")).Text, "test");
    // 45 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(2) | test
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(2)")).Text, "test");
    // 46 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(3) | 18
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(3)")).Text, "18");
    // 47 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(4) | test@test.com
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(4)")).Text, "test@test.com");
    // 48 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(5) | 19
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(5)")).Text, "19");
    // 49 | assertText | css=.rt-tr-group:nth-child(3) .rt-td:nth-child(6) | 20
    Assert.Equal(driver.FindElement(By.CssSelector(".rt-tr-group:nth-child(3) .rt-td:nth-child(6)")).Text, "20");
  }
}
